# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main    # Update this if your primary branch is named differently
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref }}   # Ensures only one deployment runs per branch at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --app named-entity-recognition  # "--app your-app-name" specifies the app if multiple apps exist
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Ensure this token is set in your GitHub repo's secrets
